dependencies:
  - allOf:
      - cert-manager
      - monitoring-crds
      - postgres-operator
      - postgres-image
environmentKinds:
  - tenant
values:
  controllerManager.container.image.tag:
    displayName: Image tag
    config:
      type: string
  postgresStorageClass:
    description: Storage class for Postgres ("standard-rwo" (default) or "premium-rwo")
    config:
      type: string
  google.projectId:
    displayName: Google project ID
    computed:
      template: '"{{.Env.project_id}}"'
  walGsBucket:
    displayName: WAL GCS bucket name
    computed:
      template: '"{{.Env.postgres_backup_bucket_name}}"'
  resyncIAMPermissions:
    displayName: Resync IAM permissions
    description: Enable resyncing of IAM permissions by recreating IAMPolicyMember resources
    config:
      type: bool
