dependencies:
  - allOf:
      - aiven-operator
      - cert-manager
      - monitoring-crds
      - postgres-operator
      - postgres-image
environmentKinds:
  - tenant
values:
  controllerManager.container.image.tag:
    displayName: Image tag
    config:
      type: string
  google.projectId:
    displayName: Google project ID
    computed:
      template: '"{{.Env.project_id}}"'
  resyncIAMPermissions:
    displayName: Resync IAM permissions
    description: Enable resyncing of IAM permissions by recreating IAMPolicyMember resources
    config:
      type: bool
  aiven.project:
    displayName: Aiven project name
    computed:
      template: "{{.Env.aiven_project | quote}}"
  aiven.projectVPCID:
    displayName: Aiven project VPC ID
    computed:
      template: '{{(splitList "/" .Env.aiven_project_vpc_id | last) | quote}}'
  aiven.metricsDestinationEndpointID:
    displayName: Aiven metrics destination endpoint ID
    computed:
      template: '{{(splitList "/" .Env.aiven_prometheus_endpoint_id | last) | quote}}'
  # CNPG settings
  cnpg.walBucketPrefix:
    displayName: Prefix to use for WAL storage buckets
    computed:
      # Max length 27 characters, to allow for 36 character uid for a total of 63 characters
      template: 'nais-wal-{{ trunc 8 .Tenant.Name }}-{{ trunc 8 .Env.name }}-'
  cnpg.walBucketRole:
    displayName: Role to give clusters for WAL storage access
    computed:
      # Max length 27 characters, to allow for 36 character uid for a total of 63 characters
      template: 'projects/{{ .Env.cnpg_wal_project_id }}/roles/CNRMRoleForCNPGClusters'
  # Zalando settings
  postgresStorageClass:
    description: Storage class for Zalando Postgres ("standard-rwo" (default) or "premium-rwo")
    config:
      type: string
  walGsBucket:
    displayName: WAL GCS bucket name
    computed:
      template: '"{{.Env.postgres_backup_bucket_name}}"'
