postgresStorageClass: ""
walGsBucket: ""
dryRun: false
development: false

google:
  projectId: ""
  location: "europe-north1"

cnpg:
  imageCatalogName: "cloudnative-image-catalog"
  storageClass: "hyperdisk-balanced"
  walBucketNamespace: "nais-cnpg-wal-storage"
  walBucketRole: ""
  walBucketPrefix: ""

# [MANAGER]: Manager Deployment Configurations
controllerManager:
  replicas: 1
  container:
    image:
      repository: europe-north1-docker.pkg.dev/nais-io/nais/images/pgrator
      tag: "latest"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 192Mi
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      httpGet:
        path: /healthz
        port: 8081
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      httpGet:
        path: /readyz
        port: 8081
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 10
  serviceAccountName: pgrator
  leaderElection:
    enable: true

# [RBAC]: To enable RBAC (Permissions) configurations
rbac:
  enable: true
  # Primary resources - CRDs owned/reconciled by pgrator (full CRUD)
  # The template auto-generates /finalizers and /status subresource rules
  # When adding resources, ensure that you're using the *plural* form of the resource name
  primaryResources:
    - apiGroups: [data.nais.io]
      resources: [postgres]
    - apiGroups: [nais.io]
      resources: [valkeys, opensearches]

# [METRICS]: Set to true to generate manifests for exporting metrics.
# To disable metrics export set false, and ensure that the
# ControllerManager argument "--metrics-bind-address=:8443" is removed.
metrics:
  enable: true

# [PROMETHEUS]: To enable a ServiceMonitor to export metrics to Prometheus set true
prometheus:
  enable: true

# [CERT-MANAGER]: To enable cert-manager injection to webhooks set true
certmanager:
  enable: true

# [WEBHOOK]: To enable validating webhooks set true
webhook:
  enable: true

# [IAM]: To enable resyncing of IAM permissions by recreating IAMPolicyMember resources set true
resyncIAMPermissions: false

aiven:
  project: ""
  projectVPCID: ""
  metricsDestinationEndpointID: ""

fasit:
  tenant:
    name: ""
