{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: pgrator-manager-role
rules:
- apiGroups:
  - data.nais.io
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.nais.io
  resources:
  - postgres/finalizers
  verbs:
  - update
- apiGroups:
  - data.nais.io
  resources:
  - postgres/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - nais.io
  resources:
    - valkeys
    - opensearches
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - nais.io
  resources:
    - valkeys
    - opensearches
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - nais.io
  resources:
    - valkeys/finalizers
    - opensearches/finalizers
  verbs:
    - update
- apiGroups:
    - nais.io
  resources:
    - valkeys/status
    - opensearches/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - aiven.io
  resources:
    - valkeys
    - opensearches
    - serviceintegrations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - monitoring.coreos.com
  resources:
    - prometheusrules
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - acid.zalan.do
  resources:
    - postgresqls
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - iam.cnrm.cloud.google.com
  resources:
    - iampolicymembers
    - iamserviceaccounts
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - ""
  resources:
    - serviceaccounts
    - namespaces
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
- apiGroups:
    - ""
    - events.k8s.io
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - authorization.k8s.io
  resources:
    - subjectaccessreviews
  verbs:
    - create
- apiGroups:
    - authentication.k8s.io
  resources:
    - tokenreviews
  verbs:
    - create
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebinding
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
{{- end -}}
