{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: pgrator-manager-role
rules:
# Primary resources - CRDs owned/reconciled by pgrator
# Auto-generates main resource + /finalizers and /status subresource rules
{{- range .Values.rbac.primaryResources }}
- apiGroups:
  {{- toYaml .apiGroups | nindent 2 }}
  resources:
  {{- toYaml .resources | nindent 2 }}
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups:
  {{- toYaml .apiGroups | nindent 2 }}
  resources:
  {{- range .resources }}
  - {{ . }}/finalizers
  {{- end }}
  verbs: [update]
- apiGroups:
  {{- toYaml .apiGroups | nindent 2 }}
  resources:
  {{- range .resources }}
  - {{ . }}/status
  {{- end }}
  verbs: [get, patch, update]
{{- end }}

# Managed resources - child resources created/owned by controllers
{{- range .Values.rbac.managedResources }}
- apiGroups:
  {{- toYaml .apiGroups | nindent 2 }}
  resources:
  {{- toYaml .resources | nindent 2 }}
  verbs: [create, delete, get, list, patch, update, watch]
{{- end }}

# Controller runtime requirements
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: ["", events.k8s.io]
  resources: [events]
  verbs: [create, patch]
# TODO: these seem to be unused? possibly a remnant from kube-rbac-proxy?
- apiGroups: [authorization.k8s.io]
  resources: [subjectaccessreviews]
  verbs: [create]
- apiGroups: [authentication.k8s.io]
  resources: [tokenreviews]
  verbs: [create]
{{- end -}}
