{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: pgrator-manager-role
rules:
- apiGroups:
  - data.nais.io
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.nais.io
  resources:
  - postgres/finalizers
  verbs:
  - update
- apiGroups:
  - data.nais.io
  resources:
  - postgres/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
