package v1

import (
	"github.com/nais/pgrator/pkg/api"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PostgresAccessLevel is the database access level requested for a personal access.
type PostgresAccessLevel string

const (
	PostgresAccessLevelRead            PostgresAccessLevel = "read"
	PostgresAccessLevelReadWrite       PostgresAccessLevel = "readwrite"
	PostgresAccessLevelReadWriteCreate PostgresAccessLevel = "readwritecreate"
)

// PostgresAccessSpec defines one immutable, time-limited personal access request.
type PostgresAccessSpec struct {
	// PostgresInstance is the explicitly selected physical database instance.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="postgresInstance is immutable"
	PostgresInstance string `json:"postgresInstance"`

	// Username is the authenticated NAIS user's email address, used verbatim as
	// the PostgreSQL role name. Must be non-empty and at most 63 bytes.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="username is immutable"
	Username string `json:"username"`

	// AccessLevel is the requested database access level.
	// +kubebuilder:validation:Enum=read;readwrite;readwritecreate
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="accessLevel is immutable"
	AccessLevel PostgresAccessLevel `json:"accessLevel"`

	// ExpiresAt is the absolute time at which this access expires.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="expiresAt is immutable"
	ExpiresAt metav1.Time `json:"expiresAt"`

	// ClientWireGuardPublicKey is the ephemeral public key generated by the CLI.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="clientWireGuardPublicKey is immutable"
	ClientWireGuardPublicKey string `json:"clientWireGuardPublicKey"`
}

// PostgresAccessTunnelStatus exposes the API-safe subset of the Tunnel status
// that callers (nais-api/CLI) need to surface a connection endpoint to the user.
type PostgresAccessTunnelStatus struct {
	// Name is the Tunnel resource owned by this PostgresAccess.
	Name string `json:"name,omitempty"`
	// Endpoint is the gateway endpoint the client should connect to.
	Endpoint string `json:"endpoint,omitempty"`
	// GatewayPublicKey is the gateway's WireGuard public key.
	GatewayPublicKey string `json:"gatewayPublicKey,omitempty"`
	// Phase is the high-level Tunnel phase reported by tunnel-operator.
	Phase string `json:"phase,omitempty"`
	// Ready reports whether the Tunnel is ready for the client to connect.
	Ready bool `json:"ready,omitempty"`
}

// PostgresAccessStatus defines the observed state of PostgresAccess.
type PostgresAccessStatus struct {
	api.BaseStatus `json:",inline"`

	// CredentialSecretName is the name of the controller-owned Secret that
	// holds the short-lived database credentials for this access.
	// +optional
	CredentialSecretName string `json:"credentialSecretName,omitempty"`

	// DatabaseRole is the stable PostgreSQL identity for this access.
	// +optional
	DatabaseRole string `json:"databaseRole,omitempty"`

	// ServerName is the TLS verification hostname the client should use for
	// the created Tunnel target.
	// +optional
	ServerName string `json:"serverName,omitempty"`

	// Tunnel is the connection status for the Tunnel owned by this access.
	// +optional
	Tunnel PostgresAccessTunnelStatus `json:"tunnel,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={nais}
// +kubebuilder:printcolumn:name="PostgresInstance",type="string",JSONPath=".spec.postgresInstance"
// +kubebuilder:printcolumn:name="Username",type="string",JSONPath=".spec.username"
// +kubebuilder:printcolumn:name="Last reconcile",type="string",JSONPath=".status.reconcileTime"
type PostgresAccess struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PostgresAccessSpec    `json:"spec"`
	Status *PostgresAccessStatus `json:"status,omitempty"`
}

func (p *PostgresAccess) GetCorrelationId() string {
	return p.Annotations[api.DeploymentCorrelationIDAnnotation]
}

func (p *PostgresAccess) GetStatus() api.Status {
	if p.Status == nil {
		p.Status = &PostgresAccessStatus{}
	}
	return p.Status
}

// +kubebuilder:object:root=true
type PostgresAccessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PostgresAccess `json:"items"`
}

func init() {
	SchemeBuilder.Register(&PostgresAccess{}, &PostgresAccessList{})
}
