//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearch) DeepCopyInto(out *OpenSearch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(OpenSearchStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearch.
func (in *OpenSearch) DeepCopy() *OpenSearch {
	if in == nil {
		return nil
	}
	out := new(OpenSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenSearch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchHttp) DeepCopyInto(out *OpenSearchHttp) {
	*out = *in
	if in.MaxContentLength != nil {
		in, out := &in.MaxContentLength, &out.MaxContentLength
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchHttp.
func (in *OpenSearchHttp) DeepCopy() *OpenSearchHttp {
	if in == nil {
		return nil
	}
	out := new(OpenSearchHttp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchIndices) DeepCopyInto(out *OpenSearchIndices) {
	*out = *in
	if in.QueryBoolMaxClauseCount != nil {
		in, out := &in.QueryBoolMaxClauseCount, &out.QueryBoolMaxClauseCount
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchIndices.
func (in *OpenSearchIndices) DeepCopy() *OpenSearchIndices {
	if in == nil {
		return nil
	}
	out := new(OpenSearchIndices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchList) DeepCopyInto(out *OpenSearchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenSearch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchList.
func (in *OpenSearchList) DeepCopy() *OpenSearchList {
	if in == nil {
		return nil
	}
	out := new(OpenSearchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenSearchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchShardIndexingPressure) DeepCopyInto(out *OpenSearchShardIndexingPressure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchShardIndexingPressure.
func (in *OpenSearchShardIndexingPressure) DeepCopy() *OpenSearchShardIndexingPressure {
	if in == nil {
		return nil
	}
	out := new(OpenSearchShardIndexingPressure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchSpec) DeepCopyInto(out *OpenSearchSpec) {
	*out = *in
	if in.ShardIndexingPressure != nil {
		in, out := &in.ShardIndexingPressure, &out.ShardIndexingPressure
		*out = new(OpenSearchShardIndexingPressure)
		**out = **in
	}
	if in.Indices != nil {
		in, out := &in.Indices, &out.Indices
		*out = new(OpenSearchIndices)
		(*in).DeepCopyInto(*out)
	}
	if in.Http != nil {
		in, out := &in.Http, &out.Http
		*out = new(OpenSearchHttp)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchSpec.
func (in *OpenSearchSpec) DeepCopy() *OpenSearchSpec {
	if in == nil {
		return nil
	}
	out := new(OpenSearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchStatus) DeepCopyInto(out *OpenSearchStatus) {
	*out = *in
	in.BaseStatus.DeepCopyInto(&out.BaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchStatus.
func (in *OpenSearchStatus) DeepCopy() *OpenSearchStatus {
	if in == nil {
		return nil
	}
	out := new(OpenSearchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchValidator) DeepCopyInto(out *OpenSearchValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchValidator.
func (in *OpenSearchValidator) DeepCopy() *OpenSearchValidator {
	if in == nil {
		return nil
	}
	out := new(OpenSearchValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Valkey) DeepCopyInto(out *Valkey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(ValkeyStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Valkey.
func (in *Valkey) DeepCopy() *Valkey {
	if in == nil {
		return nil
	}
	out := new(Valkey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Valkey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyList) DeepCopyInto(out *ValkeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Valkey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyList.
func (in *ValkeyList) DeepCopy() *ValkeyList {
	if in == nil {
		return nil
	}
	out := new(ValkeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValkeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyPersistence) DeepCopyInto(out *ValkeyPersistence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyPersistence.
func (in *ValkeyPersistence) DeepCopy() *ValkeyPersistence {
	if in == nil {
		return nil
	}
	out := new(ValkeyPersistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeySpec) DeepCopyInto(out *ValkeySpec) {
	*out = *in
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(ValkeyPersistence)
		**out = **in
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeySpec.
func (in *ValkeySpec) DeepCopy() *ValkeySpec {
	if in == nil {
		return nil
	}
	out := new(ValkeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyStatus) DeepCopyInto(out *ValkeyStatus) {
	*out = *in
	in.BaseStatus.DeepCopyInto(&out.BaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyStatus.
func (in *ValkeyStatus) DeepCopy() *ValkeyStatus {
	if in == nil {
		return nil
	}
	out := new(ValkeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyValidator) DeepCopyInto(out *ValkeyValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyValidator.
func (in *ValkeyValidator) DeepCopy() *ValkeyValidator {
	if in == nil {
		return nil
	}
	out := new(ValkeyValidator)
	in.DeepCopyInto(out)
	return out
}
