apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: cnpg-example
  namespace: basseng
  annotations:
    postgres.nais.io/engine: cnpg
spec:
  cluster:
    allowDeletion: true
    majorVersion: "18"
    resources:
      diskSize: "4Gi"
      cpu: "100m"
      memory: "1Gi"
