{{- if .Values.webhook.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: pgrator-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pgrator-validating-webhook-configuration
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- if .Values.certmanager.enable }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/pgrator-webhook-cert
  {{- end }}
webhooks:
  - name: vopensearch.nais.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: pgrator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-nais-io-v1-opensearch
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - nais.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - opensearches
    sideEffects: None
  - name: vvalkey.nais.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: pgrator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-nais-io-v1-valkey
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - nais.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - DELETE
        resources:
          - valkeys
    sideEffects: None
  - name: vpostgresbinding.nais.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: pgrator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-nais-io-v1-postgresbinding
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - nais.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - postgresbindings
    sideEffects: None
{{- end }}
