---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: opensearch-name-length
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ["nais.io"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["opensearches"]
  validations:
    - expression: "object.metadata.name.size() <= 63 - (12 + object.metadata.namespace.size())"
      messageExpression: "'metadata.name is too long; max length is ' + string(63 - (12 + object.metadata.namespace.size())) + ' characters'"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: opensearch-name-length
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  policyName: opensearch-name-length
  validationActions:
    - Deny
