apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas:  {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: pgrator-manager
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      containers:
        - name: pgrator-manager
          env:
            {{- if and .Values.certmanager.enable .Values.metrics.enable }}
            - name: METRICS_CERT_PATH
              value: /var/run/secrets/k8s-metrics-server/metrics-certs
            {{- end }}
            - name: GOOGLE_PROJECT_ID
              value: {{ .Values.google.projectId }}
            - name: POSTGRES_STORAGE_CLASS
              value: {{ .Values.postgresStorageClass }}
            - name: POSTGRES_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: postgres_image
                  name: postgres-image
                  optional: true
            - name: AIVEN_PROJECT
              value: {{ .Values.aiven.project | quote }}
            - name: AIVEN_PROJECT_VPC_ID
              value: {{ .Values.aiven.projectVPCID | quote }}
            - name: AIVEN_METRICS_DESTINATION_ENDPOINT_ID
              value: {{ .Values.aiven.metricsDestinationEndpointID | quote }}
            - name: TENANT_NAME
              value: {{ .Values.fasit.tenant.name }}
            - name: LEADER_ELECTION_ENABLED
              value: {{ .Values.controllerManager.leaderElection.enable | quote }}
            {{- if .Values.walGsBucket }}
            - name: WAL_GS_BUCKET
              value: {{ .Values.walGsBucket }}
            {{- end }}
            {{- if .Values.resyncIAMPermissions }}
            - name: RESYNC_IAM_PERMISSIONS
              value: "{{ .Values.resyncIAMPermissions }}"
            {{- end }}
            {{- if .Values.cnpg.imageCatalogName }}
            - name: CNPG_IMAGE_CATALOG_NAME
              value: {{ .Values.cnpg.imageCatalogName }}
            {{- end }}
            {{- if .Values.cnpg.storageClass }}
            - name: CNPG_STORAGE_CLASS
              value: {{ .Values.cnpg.storageClass }}
            {{- end }}
            {{- if .Values.cnpg.backupBucket }}
            - name: CNPG_BACKUP_BUCKET
              value: {{ .Values.cnpg.backupBucket }}
            {{- end }}
            {{- if .Values.cnpg.barmanPluginName }}
            - name: CNPG_BARMAN_PLUGIN_NAME
              value: {{ .Values.cnpg.barmanPluginName }}
            {{- end }}
          image: {{ .Values.controllerManager.container.image.repository }}:{{ .Values.controllerManager.container.image.tag }}
          {{- if .Values.controllerManager.container.imagePullPolicy }}
          imagePullPolicy: {{ .Values.controllerManager.container.imagePullPolicy }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.controllerManager.container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.controllerManager.container.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.controllerManager.container.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controllerManager.container.securityContext | nindent 12 }}
          ports:
            {{- if .Values.webhook.enable }}
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            {{- end }}
          volumeMounts:
            {{- if and .Values.metrics.enable .Values.certmanager.enable }}
            - name: metrics-certs
              mountPath: /var/run/secrets/k8s-metrics-server/metrics-certs
              readOnly: true
            {{- end }}
            {{- if and .Values.webhook.enable .Values.certmanager.enable }}
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
            {{- end }}
      securityContext:
        {{- toYaml .Values.controllerManager.securityContext | nindent 8 }}
      serviceAccountName: {{ .Values.controllerManager.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.controllerManager.terminationGracePeriodSeconds }}
      volumes:
        {{- if and .Values.metrics.enable .Values.certmanager.enable }}
        - name: metrics-certs
          secret:
            secretName: pgrator-metrics-server-cert
        {{- end }}
        {{- if and .Values.webhook.enable .Values.certmanager.enable }}
        - name: webhook-certs
          secret:
            secretName: pgrator-webhook-server-cert
        {{- end }}
