name: Build and deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - "*.md"

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    uses: nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@main # ratchet:exclude
    secrets: inherit
    with:
      mise-tasks: '["tidy-check", "fmt-check", "generate-check", "lint", "vet", "check", "test-race", "helm-lint"]'
      builds-docker: true
      builds-chart: true
      chart-repo: "nais-io/nais/feature"
      deploys-to-fasit: true

  documentation:
    name: Update documentation
    if: github.ref == 'refs/heads/main'
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          path: pgrator
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # ratchet:jdx/mise-action@v3
      - name: Generate documentation
        working-directory: pgrator
        run: mise run generate:doc
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # ratchet:actions/create-github-app-token@v2
        id: get-token
        with:
          app-id: ${{ secrets.NAIS_APP_ID }}
          private-key: ${{ secrets.NAIS_APP_PRIVATE_KEY }}
          repositories: doc
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          repository: nais/doc
          token: ${{ steps.get-token.outputs.token }}
          path: naisdoc
      - name: Commit documentation to nais/doc
        working-directory: naisdoc
        run: |
          cp -v ../pgrator/doc/output/data.nais.io/v1/postgres/reference.md docs/persistence/postgresql/reference/postgres-spec.md
          cp -v ../pgrator/doc/output/data.nais.io/v1/postgres/example.md docs/persistence/postgresql/reference/postgres-example.md

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git --no-pager diff --cached
          if [ ! -z "$(git diff --cached)" ]; then
            git commit -a --author "$GITHUB_ACTOR <$GITHUB_ACTOR@users.noreply.github.com>" \
              -m "postgres: automatic update of reference spec and example" \
              -m "Ref: https://github.com/nais/pgrator/commit/${GITHUB_SHA}"
            git push
          else
            echo "No changes; skip commit"
          fi
