[env]
_.source = ".config/mise/extract_env.sh"
PGRATOR_IMAGE = "europe-north1-docker.pkg.dev/nais-io/nais/images/pgrator:latest"
PGRATOR_TTL_IMAGE = "ttl.sh/pgrator:1h"

[tools]
golangci-lint = "2.10.1"
kube-controller-tools = "0.19.0"
"aqua:kyverno/chainsaw" = "0.2.12"
lefthook = "latest"
kind = "0.29.0"
tilt = "0.33.22"
setup-envtest = """
{%- set tool = '"\\ssigs.k8s.io/controller-runtime\\s"' -%}
{%- set version_fmt = '"%d.%d"' -%}
{%- set command = "grep " ~ tool ~ " " ~ config_root ~ "/go.mod | awk -F. '{printf " ~ version_fmt ~ ", $3, $4}'" -%}

{{- exec(cache_key="setup-envtest", command=command) -}}
"""
go = """
{%- set command = 'grep "^go [0-9]*\\.[0-9]*" ' ~ config_root ~ "/go.mod | awk '{print $2}'" -%}

{{- exec(cache_key="go", command=command) -}}
"""
helm = "latest"
yq = "4.50.1"
ctlptl = "latest"
