[env]
_.source = ".config/mise/extract_env.sh"
PGRATOR_IMAGE = "europe-north1-docker.pkg.dev/nais-io/nais/images/pgrator:latest"
PGRATOR_TTL_IMAGE = "ttl.sh/pgrator:1h"


[tools]
golangci-lint = "2.4.0"
kube-controller-tools = "0.19.0"
kubebuilder = "4.9.0"
setup-envtest = """
{%- set tool = '"\\ssigs.k8s.io/controller-runtime\\s"' -%}
{%- set version_fmt = '"%d.%d"' -%}
{%- set command = "grep " ~ tool ~ " " ~ config_root ~ "/go.mod | awk -F. '{printf " ~ version_fmt ~ ", $3, $4}'" -%}

{{- exec(cache_key="setup-envtest", command=command) -}}
"""
go = """
{%- set command = 'grep "^go [0-9]*\\.[0-9]*" ' ~ config_root ~ "/go.mod | awk '{print $2}'" -%}

{{- exec(cache_key="go", command=command) -}}
"""
helm = "latest"
yq = "4.50.1"

### Development

[tasks.generate]
description = "Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations."
run = [
	'controller-gen +object paths="./..."',
	'controller-gen crd rbac:roleName=manager-role webhook paths="./pkg/api/..." output:crd:artifacts:config=config/crd/bases',
	'cp config/crd/bases/*.yaml charts/pgrator/templates/crd/',
	'for f in charts/pgrator/templates/crd/*.yaml; do yq e -i "select(.kind==\"CustomResourceDefinition\") | .metadata.annotations.\"helm.sh/resource-policy\"=\"keep\"" "$f"; done',
]

[tasks.generate-doc]
description = "Generate documentation for nais/doc"
run = '''
	mkdir -p doc/output
	go run cmd/docgen/docgen.go \
		--api-dir ./pkg/api/... \
		--output-dir doc/output \
		--template-dir doc/templates
'''

[tasks.fmt]
description = "Run go fmt against code."
run = "go fmt ./..."

[tasks.vet]
description = "Run go vet against code."
run = "go vet ./..."

[tasks.helm-lint]
description = "Lint helm charts"
run = "helm lint --strict ./charts/pgrator"

[tasks.lint]
description = "Run golangci-lint linter"
run = "golangci-lint run"

[tasks.lint-fix]
description = "Run golangci-lint linter and perform fixes"
run = "golangci-lint run --fix"

[tasks.lint-config]
description = "Verify golangci-lint linter configuration"
run = "golangci-lint config verify"

[tasks.checks]
depends = ["lint", "fmt", "vet", "helm-lint"]

[tasks.setup-envtest]
description = "Setup envtest binaries"
run = "setup-envtest use ${ENVTEST_K8S_VERSION} -p path"

[tasks.test]
depends = ["generate"]
description = "Run tests."
run = """
#!/usr/bin/env bash
KUBEBUILDER_ASSETS="$(setup-envtest use ${ENVTEST_K8S_VERSION} -p path)"
export KUBEBUILDER_ASSETS
declare -a output_flags
if [[ "${GITHUB_ACTIONS}" == "true" ]]; then
  output_flags+=("--github-output")
fi
go run github.com/onsi/ginkgo/v2/ginkgo run -r --keep-going "${output_flags[@]}"
"""

### Build

[tasks.build]
depends = ["checks", "generate"]
description = "Build manager binary."
run = "go build -o bin/manager cmd/main.go"

[tasks.run]
depends = ["checks", "generate"]
description = "Run a controller from your host."
run = "go run ./cmd/main.go"

[tasks.docker-build]
description = "Build docker image for the manager"
run = "docker buildx build --load --tag ${PGRATOR_IMAGE} ."

[tasks._builder]
hide = true
run = "docker buildx create --name pgrator-builder --node pgrator-builder0"

[tasks._cleanup_builder]
hide = true
run = "docker buildx rm pgrator-builder"

[tasks.docker-multi]
description= "Build and push docker image for the manager for cross-platform support"
depends = ["_builder"]
depends_post = ["_cleanup_builder"]
run = "docker buildx build --builder pgrator-builder --push --platform=linux/arm64,linux/amd64 --tag ${PGRATOR_TTL_IMAGE} ."
